### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ' nan' when receiving MX_ST_ERROR_GRIPPER

### ISSUE THREAD

**Issue by eliapellegrino** [Mecademic/mecademicpy#7]
We are using: 

- **mecademic 500 r3, with FW version 8.4.5**
- **schunk gripper provided with the box**
- **mecademicpy** python API to command the robot

After using the robot for few minutes, we encounted this error:
```
[ERROR] [1651746262.194548]: Received robot error 3025 (MX_ST_ERROR_GRIPPER): Gripper error.
```
Attempting to clear the error, as suggested by the API:
```
# Attempt to clear error if robot is in error.
        if self.robot.GetStatusRobot().error_status:
            self.robot.ResetError()
            self.robot.ResumeMotion()

```
we get this error:
```

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tree/mecademic_catkin_ws/venv3.9/lib/python3.9/site-packages/mecademicpy/robot.py", line 1535, in _deactivate_on_exception
    raise e
  File "/home/tree/mecademic_catkin_ws/venv3.9/lib/python3.9/site-packages/mecademicpy/robot.py", line 1531, in _deactivate_on_exception
    return func(*args, **kwargs)
  File "/home/tree/mecademic_catkin_ws/venv3.9/lib/python3.9/site-packages/mecademicpy/robot.py", line 4386, in _monitor_handler
    self._handle_common_messages(response)
  File "/home/tree/mecademic_catkin_ws/venv3.9/lib/python3.9/site-packages/mecademicpy/robot.py", line 4619, in _handle_common_messages
    timestamp, index, *measurements = _string_to_numbers(response.data)
  File "/home/tree/mecademic_catkin_ws/venv3.9/lib/python3.9/site-packages/mecademicpy/robot.py", line 56, in _string_to_numbers
    return [(float(x) if ('.' in x) else int(x)) for x in input_string.split(',')]
  File "/home/tree/mecademic_catkin_ws/venv3.9/lib/python3.9/site-packages/mecademicpy/robot.py", line 56, in <listcomp>
    return [(float(x) if ('.' in x) else int(x)) for x in input_string.split(',')]
ValueError: invalid literal for int() with base 10: ' nan'
```
What could cause this? Is it our implementation wrong or maybe a mismatch between robot and gripper firmware?

**Comment by gbmecademic** [comment]
I could be a version mismatch but this looks like the gripper was disconnected while the robot was in operation. This can happen if the cable is not screwed in tight enough on the robot or the gripper, especially since you encountered a gripper error. I think that after that the API got confused because the gripper was no longer there and it is not possible to hot plug it.

Make sure the cable is really screwed in as much as you can, sometimes it can look ok but still not be correct. If this happens again I would suggest to oopen our web interface and try to connect to the robot and test if the gripper still works.

Also make sure you have the latest mecademicpy version, I think you should be ok if it worked before the gripper error but I want to make sure.

**Comment by gbmecademic** [comment]
Closing this issue since I haven't heard back and was not reproduced by someone else.
